@TodoListApi_HostAddress = http://localhost:5101

GET {{TodoListApi_HostAddress}}/api/TodoList/
content-type: application/json

### GET all todo items

POST {{TodoListApi_HostAddress}}/api/TodoList/
content-type: application/json
{
  "title": "Sample Todo Item",
  "status": "pending"  
}

### Add todo item

PUT {{TodoListApi_HostAddress}}/api/TodoList/1
content-type: application/json

### Edit todo item

DELETE {{TodoListApi_HostAddress}}/api/TodoList/1
content-type: application/json

### Delete todo item

